  - postgresql_user: name={{ data_db_user }} password={{data_db_password}} role_attr_flags=CREATEDB,CREATEROLE,CREATEUSER
    sudo: yes
    sudo_user: postgres

  - postgresql_db: name={{ data_db_name }} login_host={{ data_db_host }} login_user={{ data_db_user }} login_password={{ data_db_password }}
    sudo: yes
    sudo_user: postgres

  - name: Pull in the application
    git: repo="https://github.com/DemocracyApps/cbe-dataserver.git" force={{ git_force }} version={{ data_branch }} dest="/var/www/{{app_name}}"
    sudo: yes
    sudo_user: "{{web_user}}"

  - name: Create the vendor directory
    file: path=/var/www/{{app_name}}/vendor state=directory mode=0777
    sudo: yes

  - name: Make the vendor subdirectories writeable
    file:
      path: /var/www/{{app_name}}/vendor
      state: directory
      mode: u=rwX,g=rwX,o=rwX
      recurse: yes

  - name: Run composer install
    composer: command=install no_dev=no working_dir=/var/www/{{app_name}}
    sudo: yes
    sudo_user: "{{web_user}}"

  - name: copy .env.example to .env
    copy:
      src=/var/www/{{app_name}}/.env.example dest=/var/www/{{app_name}}/.env

  - name: Run the migration
    command: php artisan migrate
    sudo: yes
    sudo_user: "{{web_user}}"
    args:
      chdir: /var/www/{{ app_name }}


  - name: Create the data directory
    file: path={{data_directory}} state=directory mode=0777
    sudo: yes

  - name: Add cron job to run artisan
    cron: name="Artisan scheduler" user="{{web_user}}" minute="*" job="/usr/bin/php /var/www/{{app_name}}/artisan schedule:run >> /dev/null 2>&1"



