---

  - name: update apt cache
    apt: update_cache=yes upgrade=yes

  - name: Create alias /usr/bin/node -> /usr/bin/nodejs ... Grr
    file: src=/usr/bin/nodejs dest=/usr/bin/node owner=root group=root state=link

  - name: install bower
    npm: name=bower global=yes

  - name: install gulp
    npm: name=gulp global=yes



