---
- hosts: all
  sudo: true

  vars:


  vars_files:
    - common_vars.yml

  pre_tasks:

  - name: update apt cache
    apt: update_cache=yes

  roles:
    - common    # Install standard software on the server
    - webserver # Install & configure Apache & PHP
    - { role: vhost, app_name: "cbe", app_port: 80}
    - { role: vhost, app_name: "drs", app_port: 10010 }

#    - vhost     # Create a virtual host associated with the application
#    - { role: database, when: role == 'development' }
#    - { role: database_client, when: role != 'development' }
#    - awscli
#    - ebs_backup




